[server]
headless = true
port = 8501
enableCORS = false
runOnSave = true

[theme]
primaryColor = "#636EFA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[ui]
# デフォルトのページナビゲーションを無効化
hideTopBar = true

